### ISSUE TITLE
Epic - Support configuration updates in free5GC operator

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#100]
Support configuration update operators that can update the free5gc configuration and reload it. Mainly we are focussing on horizontal configuration  scale out changes,

- [x] #101
- [x] #102

**Comment by tliron** [comment]
See [Reloader](https://github.com/stakater/Reloader).

**Comment by johnbelamaric** [comment]
@n2vo - debugging SMF updates; will reach out to @s3wong tonight if stuck

**Comment by johnbelamaric** [comment]
I think this is done, right?

**Comment by johnbelamaric** [comment]
Yeah, just checked, it is done. We will need e2e tests but that's a separate issue.
