### ISSUE TITLE
Epic - Support other free5gc network functions

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#104]
Support other free5gc functions .
Refer to these as provided by Orange team.

Also references:
[Presentation](https://drive.google.com/drive/folders/1WXxeOvkR4M_PpPIDe-HgLc-TjY9YvrMr) 
Custom kpt packages: [kpt packages catalog](https://github.com/matysiaq/kpt-packages-catalog)
Improved free5gc-operator: [free5gc-operator](https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator)
Reference helm charts: [Towards5gs](https://github.com/Orange-OpenSource/towards5gs-helm)

- [x] #105
- [x] #106

**Comment by johnbelamaric** [comment]
Test 003 in https://github.com/nephio-project/test-infra/pull/63 automates this

**Comment by johnbelamaric** [comment]
Done!
