### ISSUE TITLE
Test to ensure all free5GC NFs are running

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#106]
Test to ensure all free5gc NFs are running. This is to make sure all NFs are running on the edge clusters.. This effort is targeted towards making sure the rst of NFs ( in addition to SMF, UPF, AMF) are running successfully on the edge clusters which is deployed with complete shift left mechanism. This effort is not about test automation rather manual verification of the new package deployment.

[Parent](https://github.com/nephio-project/nephio/issues/104) issue.

**Comment by johnbelamaric** [comment]
Done (manual testing), but we need automated e2e for this.
