### ISSUE TITLE
Package to provision KinD clusters via CAPI

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#108]
Develop package to provision clusters

**Comment by johnbelamaric** [comment]
See https://github.com/nephio-project/nephio/issues/168#issuecomment-1548099578 for a description of how all the pieces fit together.

**Comment by johnbelamaric** [comment]
/retitle Package to provision KinD clusters via CAPI

**Comment by johnbelamaric** [comment]
Fixed by https://github.com/nephio-project/nephio-example-packages/pull/10
