### ISSUE TITLE
Cluster Bootstrap Controller to install Config Sync, WatcherAgent

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#109]
Implement Cluster Bootstrap Controller to install Config Sync, WatcherAgent on edge clusters.
Document the design and functionality
Unit test coverage

**Comment by henderiw** [comment]
available, one last PR to be approved

https://github.com/nephio-project/nephio/pull/212

**Comment by johnbelamaric** [comment]
/retitle Cluster Bootstrap Controller

This done and working. We will need a new issue to integrate WatcherAgent.

**Comment by johnbelamaric** [comment]
#246
