### ISSUE TITLE
Create vendor neutral CRDs for Network Functions

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#11]
Create vendor neutral CRDs and Go types for Network functions. 
See [this](https://docs.google.com/document/d/1cD-Lo-isvi1vN-G_TimPqIEU_eXp2H3a9vUIaAyH6Ug/edit) document for reference and details. 

As part of this we need to define CRDs for SMF, UPF and AMF.
Following are the task list
- [x] Create CRDs for UPF (UPF class and deployment)
- [x] Create CRDs for SMF (SMF class and deployment)
- [x] Create CRDs for AMF (AMF class and deployment)

**Comment by johnbelamaric** [comment]
This is done.
