### ISSUE TITLE
Include OSS license vetting tool that supports Go

### ISSUE THREAD

**Issue by tliron** [nephio-project/nephio#114]
Are all our transitive and intransitive imports compatible with the Apache License?

There are tools that can be included in our Prow pipeline to validate this.

**Comment by gvbalaji** [comment]
Good point @tliron . Do you have any suggestions on such tools? @radoslawc any suggestions?

**Comment by gvbalaji** [comment]
Thanks @radoslawc

**Comment by radoslawc** [comment]
Implemented scancode-toolkit integration and checking resulting binary for linked dependencies and their licenses via lichen. All done in lab so far.
