### ISSUE TITLE
Porch PackageVariant Kptfile pipeline editing feature

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#117]
Part of the PV design in #36 - see https://github.com/GoogleContainerTools/kpt/blob/main/docs/design-docs/08-package-variant.md#krm-function-pipeline1

**Comment by SimonTheLeg** [comment]
Short update on this. In order to merge https://github.com/GoogleContainerTools/kpt/pull/3925 in an elegant way, the following two upstream contributions are required:
- https://github.com/kubernetes-sigs/kustomize/pull/5145
- https://github.com/kubernetes-sigs/cli-utils/pull/619

**Comment by johnbelamaric** [comment]
Any updates here, @SimonTheLeg ?

**Comment by SimonTheLeg** [comment]
Unfortunately not. I am really struggling with the editing via kyaml. I have it now to a point where it is possible to append to an existing map and it will keep the seqIndentStyle, but now it is struggling with appending if the list was empty before. In a nutshell: either I am missing something quite obvious or this is really complicated to do. In any case: I'll give it another shot today and will push what I have at the end of the day. And then we can have a look either after sig-automation today or pkg-mgmt subproject tomorrow

**Comment by johnbelamaric** [comment]
Are you using the kpt function SDK? It makes this a lot easier, once you understand it. Take a look at how I did the ConfigMap changes in the package context code, or later today I can provide an example another PR I am working on.

**Comment by johnbelamaric** [comment]
Yeah, good point about the comments. @kispaljr I believe has an update to the SDK that preserves comments better. We can get that integrated at some point. I am OK with forgoing that and treating it as an SDK bug that needs fixing, for now. In other words, I would just go ahead and use the SDK for now. You are right the way I do it in the link is not the best, for these reasons, and also should be fixed. I am more interested in getting the critical path going; we can perfect it later (though we should capture it in an issue).

**Comment by johnbelamaric** [comment]
This PR may be helpful to you as well: https://github.com/GoogleContainerTools/kpt/pull/3940
