### ISSUE TITLE
UI: Implement viewer for in-package PackageVariantSet resource

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#120]
Implement UI resource editors for PackageVariantSet.
Unit test coverage.

[Parent](https://github.com/nephio-project/nephio/issues/107) issue

**Comment by johnbelamaric** [comment]
/retitle Implement viewer for in-package PackageVariantSet resource

**Comment by johnbelamaric** [comment]
/retitle UI: Implement viewer for in-package PackageVariantSet resource

**Comment by ganchandrasekaran** [comment]
Created a fake PVS yaml here for DEV purpose:
https://github.com/ganchandrasekaran/nephio-example-packages-ui-test/blob/main/free5gc-smf-org-example/packagevariantset.yaml

**Comment by chander12shekhar** [comment]
Here is a Viewer implementation for PVS,
@johnbelamaric @ChristopherFry please let know if any changes are need?

![PVS1](https://github.com/nephio-project/nephio/assets/9456572/5bcb36ec-4d53-4e37-9bd9-55a04064b481)
![PVS2](https://github.com/nephio-project/nephio/assets/9456572/87f1f6e0-8146-4a67-9cec-1694814b633f)

**Comment by ganchandrasekaran** [comment]
@ChristopherFry  @johnbelamaric  Here is PR for review: https://github.com/nephio-project/kpt-backstage-plugins/pull/3
