### ISSUE TITLE
Create CRDs for Network Instance Set

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#13]
Create CRDs for Network instance Set
Refer to [this](https://docs.google.com/document/d/1cD-Lo-isvi1vN-G_TimPqIEU_eXp2H3a9vUIaAyH6Ug/edit#) document

**Comment by johnbelamaric** [comment]
Closing as obsolete, as we have moved to using composition of resources inside a package, and then using PackageVariant/PackageVariantSet resources to actuate the distribution across cluster topologies.

See also https://docs.google.com/document/d/1wtA5BJnn1GGq-yWa7FUAOrCJuyQqifB3f4ky-IePIzo/edit#heading=h.atc9ypf4hfox
