### ISSUE TITLE
E2E: Make a call with UERANSIM

### ISSUE THREAD

**Issue by tliron** [nephio-project/nephio#150]
Connect our free5GC deployment to [UERANSIM](https://github.com/aligungr/UERANSIM).

No need for Nephio automation, it can be a manual script to deploy the component at the edge.

For reference, see the [towards5GS project](https://github.com/Orange-OpenSource/towards5gs-helm).

**Comment by johnbelamaric** [comment]
@denysaleksandrov on slack: this is near working https://nephio.slack.com/archives/C04S9T2Q6MT/p1685618811014389

**Comment by johnbelamaric** [comment]
- installed Nephio mgmt & one edge cluster
- pushed free5gc-cp package and those are running properly (done with Nephio)
- NRF returns service name without the namespace, so everything has to be in the same namespace (perhaps can register services with FQDN)
- Used UERANSIM helm chart (but there is a kpt pkg in nephio-example-packages)
- Call was successful!

**Comment by gvbalaji** [comment]
On  hold  until E2E test is ready.

**Comment by johnbelamaric** [comment]
The test should be added to our [e2e](https://github.com/nephio-project/test-infra/tree/main/e2e/tests) as test case 007.sh.

Next step though is to get the e2e provisioning up and working through 006.sh, then see get a call through manually. After that we can figure out what changes are needed to automate it.

/retitle E2E: Make a call with UERANSIM

**Comment by johnbelamaric** [comment]
@denysaleksandrov I added a comment that we can automate this as 007.sh, but we hadn't really discussed it. Is it something you would be able to work on?

Basically writing a little script similar to those in the tests dir that deploys / configures UERANSIM and does whatever needs to be done to make a call, assuming the e2e cluster topology of one regional and two edge clusters.

We don't *quite* have everything up and running yet - but we could still write this script, I think, so it is ready to go.

**Comment by johnbelamaric** [comment]
I think without #270 we may have trouble with this being successful. But we should go ahead with the building out the test script in parallel.

**Comment by denysaleksandrov** [comment]
For sure, without networking there will not be reachability via Nx interfaces, in this particular case ueransim will not be able to reach UPF.

**Comment by denysaleksandrov** [comment]
@johnbelamaric I will add ueransim kpt package into `free5gc-packages/ueransim`. I don't want to use helm in the script to install it. A couple of parameters are required to give to ueransim to reach AMF and UPF via N2 and N3 interfaces respectively.

**Comment by johnbelamaric** [comment]
> @johnbelamaric I will add ueransim kpt package into `free5gc-packages/ueransim`. I don't want to use helm in the script to install it. A couple of parameters are required to give to ueransim to reach AMF and UPF via N2 and N3 interfaces respectively.

I think it's already in nephio-example-packages

**Comment by denysaleksandrov** [comment]
Indeed, it's there. Will use that in my 007.sh script.

Best Regards,
Denys Aleksandrov

**Comment by denysaleksandrov** [comment]
@johnbelamaric please take a look [here](https://github.com/nephio-project/test-infra/pull/81)
Not tested yet, since the previous steps are not ready.

**Comment by johnbelamaric** [comment]
works!
