### ISSUE TITLE
Create user guide for Nephio

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#158]
Create user guide in the docs repo. The guide should cover

- Nephio  Overview (Principles and Concepts)
- Brief Overview of KPT, Porch and Configsync with links
- R1 scope
- Deployment model (management cluster, workload clusters, package management, gitops etc)
- General Workflow 
- -NB interfaces (CRDs, PVS )
- Management cluster details (role, components, functions, controllers, choreography)
- Instantiation of clusters using Nephio
- Workload cluster details (Operators, controllers)
- Core Free5gc deployment ( CRDs, deployment methods, SMF/UPF/AMF deployment)
- Deployment of other free5gc NFs ( deployment, limitations, manual procedure needed etc)
- Validation of free5gc deployment ( sessions established, pods running, pings)
- Troubleshooting and workarounds

- ..
- ..

**Comment by johnbelamaric** [comment]
cc @johnbelamaric @henderiw @tliron

**Comment by johnbelamaric** [comment]
LGTM, please put a skeleton in the docs repo
