### ISSUE TITLE
Create install/deployment guide for Nephio

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#159]
Create install/deployment guide for Nephio  in the docs repo
Should cover how to create the sandbox using the opinionated approach ( KIND clusters) as well as installing Nephio components on an existing k8s cluster. 

Contents : 

-  Overview
- Compatibility Matrix (version of k8s, OS, Docker version etc)
- Supported platforms
- Prerequisites ( software, connections, registry access, networking etc)
- Sandbox installation 
- Installation method for each supported platform  ( OS, K8s distro,) 
-  

> Management cluster setup
Workload cluster  setup

- Definition of successful installation  ( running clusters, pods, etc. How to validate it)
- Troubleshooting steps
- 

-

**Comment by johnbelamaric** [comment]
@johnbelamaric @henderiw @tliron

**Comment by johnbelamaric** [comment]
looks like a great start @gvbalaji - maybe start with this as a skeleton in https://github.com/nephio-project/docs

Another thought - should we move the Issues in the docs repo (there are only 3) to the nephio repo, and turn off issues there? I have done that with most other repos.

**Comment by gvbalaji** [comment]
Sure @johnbelamaric . I am okay moving the issues from the docs repo.

**Comment by johnbelamaric** [comment]
Cool, I think there is a magic prow command to do it, I haven't tried it before.

**Comment by gvbalaji** [comment]
I moved all the issues out of docs to Nephio.
