### ISSUE TITLE
End to End integration test repo and framework

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#161]
Ideally we need integration tests running every PR (subset) and periodically (whole set) . We need to define the integration test framework where we can add tests over a period of time.  AS part of this
- [ ] Create the repo for integration tests
- [ ] Define the end to end testing framework ( what test tools to be used etc)
- [ ] Define couple of integration tests that can serve as examples
- [ ] Set up Prow to run integration tests.

**Comment by electrocucaracha** [comment]
Does the integration test only cover the Nephio components? In other words, this will validate the communication between Porch, ConfigMap and other controllers? Are we going to use a workload for checking this interaction?

**Comment by henderiw** [comment]
For E2E we need the complete system which includes porch, config sync, etc. So we have to validate these communication. Now if they don't work, nothing will function as they provide the artefacts for the rest to function.

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/tree/main/e2e/provision#quick-start-for-gce

You can pass a metadata value to tell this to run the e2e test - but we need a recipe for how to add tests, where the results end up, tied to CI, etc.

**Comment by johnbelamaric** [comment]
@vjayaramrh to work with @radoslawc to get latest e2e scripts running in Prow and integrated
- need instructions and a place to drop e2e tests to be included in the run
-

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/pull/63

Has a little test framework, it will need work over time but gets us started. Main point Victor raised is making sure we can test PRs, not just  merged code. I think that will have to come in a later PR.

**Comment by johnbelamaric** [comment]
Done
