### ISSUE TITLE
Package specialization - Integration test framework

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#165]
Develop the integration test framework for package specialization which can help test the wntite kpt pipeline to transform input KRM resources to the actual output  KRM resources that be applied to workload clusters specifically UPFDeployment, AMFDeployment AND SMFDeployment.

**Comment by henderiw** [comment]
work in progress, almost ready but dependent on the fn PR(s).

**Comment by kispaljr** [comment]
Progress is tracked here: https://github.com/nephio-project/nephio/pull/178

**Comment by kispaljr** [comment]
@gvbalaji this was closed by accident. 
There are two PRs related to this, and only one of them was merged. Apparently this was enough for PROW to close this. I am reopening this, until the other PR is also merged.
