### ISSUE TITLE
Installer for Nephio

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#22]
Processes, tools, and other artifacts needed to build, test, and package the components and the overall Nephio solution. Document the dependencies,  process of packaging all components and installing Nephio ( preferably with a script)

We need to decide where this should reside in may be a repo  like nephio-installer or getting started. 

There is a difference between this and the sandbox we create for E2E tests. Sandbox could be the entire set up that includes KIND clusters (both management and workload) and installing packages on them including networking configuration etc, where as scope of the installer is different.  The scope should be

- Given  a k8s cluster  (could be anything ,anywhere)  which wants to act as a management cluster , how we can set up all the required components of Nephio ( possibly including Porch, kpt). Configure porch with the repos etc.
- Given a k8s cluster which acts as a workload cluster we would like to install all packages (possibly including configsync). Set up configsync repo etc
- Do step 2 in bulk to set up multiple repos.
- Do 1, 2 and 3 above with a single command by getting all the user inputs in a yaml file may be.

So E2E test bed sandbox is highly opinionated where as installer should work on any k8s cluster with possible instructions for networking setup for GRPC communications

- [x] #47
- [ ] Create the installer

**Comment by electrocucaracha** [comment]
Hi @gvbalaji , I was thinking about this one and I have some ideas that I want to try, could you assign this to me?

**Comment by johnbelamaric** [comment]
It seems "packaging" is part of SIG 2 not SIG 3 like I thought. Moving this.

**Comment by electrocucaracha** [comment]
@johnbelamaric I have some progress on this task [here](https://github.com/electrocucaracha/nephioadm), it needs more reviews and verification.

**Comment by electrocucaracha** [comment]
> Awesome, nice Victor. A few thoughts:
> 
>     1. If I create a repo in nephio-project for this, can you move it there?

Yes, this repo can be moved into nephio-project org, I have few concerns about licensing (like adding Samsung's header) and keeping or changing the method to [provision dependencies](https://github.com/electrocucaracha/nephioadm/blob/master/scripts/install.sh), currently I'm installing them through some [scripts in other project](https://github.com/electrocucaracha/pkg-mgr_scripts) which can cause some unnecessary burden.

>     2. We may want to discuss in an upcoming meeting - not sure which. I think we can put this in pkg mgmt subproject for now.

Agree, wherever that makes sense.
 
>     3. I am hoping we can "dogfood" a bit and use kpt packages to bootstrap the post-cluster creation install. I think you may already be doing that, I see kpt stuff in there.

I couldn't find a way to consume kpt API directly, so I ended [wrapping](https://github.com/electrocucaracha/nephioadm/blob/master/internal/kpt/command.go) the CLI and calling it from a [component](https://github.com/electrocucaracha/nephioadm/blob/master/internal/app/runner.go) which contains the Nephio logic. This is an initial proposal, but I'm sure there are more skillful gophers there.

>     4. I want to be sure we layer things so creating the "demo sandbox" and installing in a production cluster share the "nephio install" part. Does the tool cover both these or primarily one or the other?

For the K8s cluster(s) creation, I've separated the process in the [multi-cluster tool](https://github.com/electrocucaracha/multi-cluster) which basically uses some portion of [Antonio Ojea multicluster project](https://github.com/aojea/kind-networking-plugins/tree/main/multicluster). I'm not sure if we have to consider this other project as part of Nephio but [facilitates](https://github.com/electrocucaracha/nephioadm/blob/master/scripts/configure.sh#L29) the setup using [config files](https://github.com/electrocucaracha/multi-cluster/blob/master/scripts/config.yml) 

>     5. I am thinking, once we have cluster creation as part of Nephio, the tool can just bootstrap the environment - install the basic Nephio stuff on the mgmt cluster - and then Nephio can do the rest (e.g., workload cluster provisioning). We would be limited though by not having any solution for intercluster networking, though, unless we do that too.

The tool is inspired by kubeadm, so there are mainly two steps: [init](https://github.com/electrocucaracha/nephioadm/blob/master/scripts/configure.sh#L40-L45) and [join](https://github.com/electrocucaracha/nephioadm/blob/master/scripts/configure.sh#L49-L50). These steps will deploy Nephio services on K8s clusters which are pointed by kubeconfig

**Comment by gvbalaji** [comment]
AFter discussions with @aravind254 I have updated the description of this story. Basically how is this different from sandbox for the E2E testing? I have tried to explain and put my thoughts in the description. We should further discuss this.

**Comment by johnbelamaric** [comment]
Any update here?

**Comment by electrocucaracha** [comment]
The internal process to release the seed code is taking more than expected. We decided to create a placeholder/function for now to eventually replace the functionality in the near future.

**Comment by vjayaramrh** [comment]
@electrocucaracha @rravindran123 Per our discussion below are the steps to bring up a nephio management cluster with ansible playbooks that does not install the nephio package components

```
1. Follow the steps at link https://github.com/nephio-project/one-summit-22-workshop/tree/main/nephio-ansible-install#installation.
    1.1 When creating the inventory/nephio.yaml file, comment out clusters->edge1, clusters->edge2, clusters->region1
2. Next, follow instructions at https://github.com/nephio-project/one-summit-22-workshop/tree/main/nephio-ansible-install#deploy-nephio-environment by applying skip-tags as below
    2.1 ansible-playbook playbooks/install-prereq.yaml —skip-tags nephio
    2.2 ansible-playbook playbooks/deploy-clusters.yaml —skip-tags Nephio
3. Optionally, you can install either create the github repos (3.1) or gitea repos (3.2.1 and 3.2.2)
   3.1 ansible-playbook playbooks/create-repos.yaml
   3.2.1 ansible-playbook playbooks/create-gitea.yaml
   3.2.2 ansible-playbook playbooks/create-gitea-repos.yaml
```

**Comment by johnbelamaric** [comment]
Can we get a little user guide and a link to how to do this, then we can close this issue?

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/tree/main/e2e/provision#quick-start-for-gce

Is sufficient for this issue
