### ISSUE TITLE
nephio-controller-manager: missing Gitea secret stalls startup forever

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#221]
If the secret is not available (or some other startup issue occurs), then this line:

https://github.com/nephio-project/nephio/blob/31b37fcf142b3b84c7d7980d28d777bdf784d85a/operators/nephio-controller-manager/main.go#L105

Never returns. Instead, this should be done in a Go routine, and we should throw errors if it's not initialized and someone tries to use it.

```
ubuntu@nephio-r1-e2e:~$ k -n nephio-system logs -c controller nephio-controller-7cb6bd884d-c2dn6
I0527 15:45:11.452645       1 listener.go:44] controller-runtime/metrics "msg"="Metrics server is starting to listen" "addr"="127.0.0.1:8080"
E0527 15:45:16.454065       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:21.454934       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:26.457843       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:31.459011       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:36.461829       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:41.462003       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:46.466309       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:51.467763       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:45:56.469867       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:46:01.471449       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:46:06.473859       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:46:11.474388       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
E0527 15:46:16.478617       1 giteaclient.go:81]  "msg"="cannot get secret" "error"="the cache is not started, can not read objects" 
ubuntu@nephio-r1-e2e:~$ 
```

/assign @ssharmasandeep

**Comment by johnbelamaric** [comment]
I am working around this for now by rebuilding, changing the line to `go g.Start(ctx)` but we should do a proper Go routine with a stop channel, etc., probably. Or perhaps run the Go routine inside the Start method. Not sure.

**Comment by ssharmasandeep** [comment]
https://github.com/nephio-project/nephio/pull/227

Please review this PR, 
however, I am not able to test end-to-end, because my dev environment has missing dependencies for ipam and vlan, I am not sure what is required to be installed and what is the ip:port both reconcilers expect as a proxy client address.  Any link to an automation script that does the same will help. 

-Sandeep

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/pull/56#issuecomment-1565196836 will set up a complete environment, but I don't have IPAM and VLAN working there yet (nor bootstrap).

In any case, that one has merged so I will close this issue and open another one if there's a problem.
