### ISSUE TITLE
nephio-operator: vlan, ipam specializers and bootstrap controller are not starting

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#229]
I am able to run a full environment using this:

https://github.com/nephio-project/test-infra/pull/56#issuecomment-1565196836

But vlan, ipam speciazers, though imported in main.go, do not seem to be coming up. Similarly bootstrap, but I think that may not even be imported (not sure).

**Comment by henderiw** [comment]
added bootstrappers
https://github.com/nephio-project/nephio/pull/232

for specializers we need access to the backend

Here is what I use normally. I never put a ctx in Setup. I initialize the proxies in main and add them via the config like we do for Gitea/porch.

backendAddress := fmt.Sprintf("%s.%s.svc.cluster.local:%s", "resource-backend-controller-grpc-svc", "backend-system", "9999")
	ctrlCfg := &ctrlrconfig.ControllerConfig{
		GiteaClient: gc,
		PorchClient: porchClient,
		IpamClientProxy: ipam.New(ctx, clientproxy.Config{
			Address: backendAddress,
		}),
		VlanClientProxy: vlan.New(ctx, clientproxy.Config{
			Address: backendAddress,
		}),
		Targets: targets.New(),
	}

**Comment by henderiw** [comment]
https://github.com/nephio-project/nephio-example-packages/pull/36

add this to enable specializers

**Comment by johnbelamaric** [comment]
fixed
