### ISSUE TITLE
E2E testing : Management cluster deployment

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#235]
Make sure all pods are up and running

**Comment by johnbelamaric** [comment]
Anh and Liam to decide which environments and create separate issues for each of those, and close this issue.

**Comment by liamfallon** [comment]
Notes of meeting on 31st May:

Deployment Options
1. Sandbox: Single VM using Kind clusters for Management cluster and workload clusters (Kicking tyres)
2. Openstack: Spin up clusters on Openstack for management cluster and workload cluster
3. Azure (Stretch): Spin up clusters on Azure for management cluster and workload cluster

Scripting support (Ansible etc) and documentation are the deliverables for each deployment options.

@gvbalaji Maybe we could create issues for each of these

**Comment by johnbelamaric** [comment]
Thanks Liam. I think we need a few more refinements. I think about it this way:

- dimension 1: what type of management cluster, and where does the mgmt cluster run? (these are two factors, but they are not independent)
- dimension 2: what types of workload clusters do we use, provisioned by what and running where?

What we have right now in the test-infra/e2e/provision directory is:
 - dimension 1: kind cluster, running in a GCE VM
 - dimension 2: kind clusters, provisioned by CAPI, running in the same GCE VM as the mgmt cluster

I think we need to figure out what other combinations we will test and document in R1. To start:

- dimension 1: kind cluster, running in a local VM
- dimension 2: kind clusters, provisiioned by CAPI, running in the same local VM as the mgmt cluster

Then, we want to see, what else can we support? A real production environment might look like:

- dimension 1: OSS K8s cluster on OpenStack
- dimension 2: OSS K8s clusters provisioned by CAPI, running in OpenStack

and

- dimension 1: GKE Autopilot cluster running in GCP
- dimension 2: GDC Edge clusters provisioned via KCC, AND GKE Cluster running in GCP provisioned via KCC, AND EKS clusters running in AWS provisioned via AWS controllers for Kubernetes

There are a zillion combinations...what can we commit to trying, getting working, and documenting?

**Comment by liamfallon** [comment]
Regarding this one:
 dimension 1: kind cluster, running in a local VM
 dimension 2: kind clusters, provisioned by CAPI, running in the same local VM as the mgmt cluster

We can verify that it works on a local VM, where the VM is running in different environments
- VM running on Openstack infrastructure (I can take this one)
- VM running on a Windows machine
- VM running on a Macbook with x86 architecture (Is this OK @n2vo ?)

**Comment by efiacor** [comment]
Regarding our plan for OpenStack:
dimension 1: OSS K8s cluster on OpenStack

Am I correct in thinking that we require a prod ready K8s stack here? ie Controller/Master node and 2+ worker nodes?

If so, we will prob use:

kubespray + ansible

Do we have a recommended spec/dimensions for the stack anywhere?

**Comment by tliron** [comment]
@efiacor I'm worried that we're jumping too far ahead here. We need a more open conversation in the community as to what it means to provision/manage/own clusters by Nephio, including management clusters. I don't think we want to create our own K8s distribution, and if we use an off-the-shelf tool it should be for demonstration/testing purposes and seen as an endorsement or a requirement. I'm already worried that some of us have gone ahead and used kpt packages to deploy edge clusters -- this is not something we discussed as a community and I'm not sure it gives the right impression to newcomers. I just don't think it's likely that Nephio will be managing a fleet of sites: that was never in our scope.

For our reference implementation KIND does the work, in my view, to demonstrate Nephio's functionality, and I'm not sure we really need more. Of course KIND will run in an OpenStack compute node, too. As the project matures I think it would make sense to consider support for various cloud platforms, especially cloud management platforms, and a variety of Kubernetes distributions, including (we hope!) official support paths from providers.

**Comment by johnbelamaric** [comment]
Managing fleets of clusters was always in scope for Nephio, just not for R1; it was a stretch for R1. Provisioning clusters in exactly this way has always been the plan. That is part of swim lane 1. 

What is NOT in scope is the actuation layer. For that, we rely on upstream projects like cluster API, KCC, etc.

**Comment by tliron** [comment]
That's what I mean -- something else is the manager and we interact with it.

**Comment by johnbelamaric** [comment]
Ah, ok. Makes sense.

**Comment by efiacor** [comment]
@tliron I think I understand your points. Very new to this project so still trying to get up to speed. 

Ultimately, we have an openstack cloud space at our disposal and would like to help out where we can.

So, maybe it would be better for the guru's/community here to discuss what the target is with regards to OpenStack and to define a rough scope for that.

These 2 in particular:

- dimension 1: OSS K8s cluster on OpenStack
- dimension 2: OSS K8s clusters provisioned by CAPI, running in OpenStack

Maybe we could discuss further at today's Scrum and/or on a slack channel.

**Comment by henderiw** [comment]
There is a lot of misunderstanding here it seems. What this task is about is trying to deploy the nephio environment on a different environment than GCP.

Right now the framework we have is this.
- A VM where we host everything (lets call this the base VM)
- What we host is: a kind cluster for mgmt and its controllers (porch/nephio-controllers, etc). This allows to configure workload clusters using CAPI as the actuator. We deploy kind clusters with this on the same base VM.

What we want to do here is this.
The base VM scripts are tailored towards GCP. What we would like is to have the base VM be instantiated on different environments like openstack, VMWare, Azure. Was, etc.

We are not talking about doing new clusters with CAPI, etc etc.

**Comment by efiacor** [comment]
Ok. Understood.
Simply a modified version of the scripts to use openstack. Got it.

**Comment by johnbelamaric** [comment]
@efiacor You mentioned that in an OpenStack Ubuntu instance, you just dig "curl .../gce_init.sh | /bin/bash".

I like that. I think we should:

- Split all but the metadata grab from `gce_init.sh` into `demo_install.sh`
- Have gce_init.sh call that demo_install.sh with the params from metadata
- Document the curl | bash with demo_install.sh
- Consider putting demo_install.sh on a more discoverable URL, imagine: `curl demo.nephio.org/install.sh | /bin/bash`
- In `demo_install.sh` we can eventually add checks for Ubuntu vs RHEL, etc.
-

**Comment by johnbelamaric** [comment]
Ok, I split off the manual runs on OpenStack, vSphere, and Mac Fusion into separate issues.

This issue can be closed as it is satisfied by our [e2e provisioning](https://github.com/nephio-project/test-infra/tree/main/e2e/provision) and test case 001.sh.
