### ISSUE TITLE
E2E Testing : Workload cluster deployment

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#236]
Make sure clusters are up and ConfigSync is deployed

**Comment by johnbelamaric** [comment]
See readme included in for https://github.com/nephio-project/test-infra/pull/56 - this is now working for GCE. It should work for other environments too, once #235 build the sandboxes for those environments.

**Comment by johnbelamaric** [comment]
@n2vo @liamfallon 

Make similar issues for each environment you plan to support - for now, this is not different cluster providers, but instead using the Kind provisioning in different environments.

**Comment by johnbelamaric** [comment]
So summarizing the decision for this and #235, scope for R1 is:

Demo/dev environment (all run in single VM with Kind clusters):
- GCE VM
- OpenStack VM
- Local VM

Bring-your-own-cluster:
- requires manual setup of all clusters, repos, and joining workload clusters to Nephio
- ideally we document and test this in a couple environments

**Comment by johnbelamaric** [comment]
Automated e2e test for GCE is in this PR: https://github.com/nephio-project/test-infra/pull/63/files

**Comment by johnbelamaric** [comment]
This issue can be closed as it is satisfied by our [e2e provisioning](https://github.com/nephio-project/test-infra/tree/main/e2e/provision) and test case 001.sh and 002.sh.
