### ISSUE TITLE
E2E testing : Deploy free5gc operator on workload cluster using Nephio

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#237]
Make sure all pods are up and running

**Comment by johnbelamaric** [comment]
Need:
 - an image with the operator
 - a kpt pkg with all the manifests to deploy the operator

Then we just need a PVS to distribute this.

**Comment by johnbelamaric** [comment]
@n2vo will follow up and create issues / assign to the right people

**Comment by johnbelamaric** [comment]
@tliron will manually build and push free5gc-operator image

**Comment by tliron** [comment]
See [here](https://hub.docker.com/r/nephio/free5gc-operator-controller).

**Comment by johnbelamaric** [comment]
Not quite done: https://github.com/nephio-project/free5gc-packages/pull/22

**Comment by johnbelamaric** [comment]
Ok, with the latest checkins I tried https://github.com/nephio-project/test-infra/pull/76 and it worked, so as soon as that merges we can mark this done.

**Comment by johnbelamaric** [comment]
That's merged, I tested it and it is working.
