### ISSUE TITLE
E2E Testing : Free5gc NF packages are deployed successfully onto workload clusters using Nephio.

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#238]
Make sure all PODs are up and running
Make sure ping works between SMF and UPF

**Comment by johnbelamaric** [comment]
Probably also need packages to represent the actual function instances, including all their requirement CRs, etc., that go through the package specialization process.

/assign @vjayaramrh 

Open issues:
- We need to integrate cluster context with the cluster creation process (update cluster package)
- We need to integrate injection of cluster context at package instantiation time (update NF packages)
-

**Comment by vjayaramrh** [comment]
@johnbelamaric @henderiw Should the value for the name field at https://github.com/nephio-project/free5gc-packages/blob/main/pkg-example-amf-bp/package-context.yaml#L8 be the name of the package i.e `pkg-example-amf-bp` instead of just `example`

**Comment by johnbelamaric** [comment]
That gets filled in automatically by kpt/Porch when the package published to a deployment repository (by Porch) or pulled with `kpt get --for-deployment`.

**Comment by vjayaramrh** [comment]
Where are the instructions to deploy the free5gc nf packages? I am looking for something similar to step 5 at https://github.com/nephio-project/test-infra/blob/main/e2e/provision/README.md

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/pull/61

**Comment by vjayaramrh** [comment]
Update on June 5th:
- As part of ensuring all pods are up and running, I found the some of the pods in the free5gc-cp namespace to be stuck in init and pending state. (cc: @johnbelamaric )
```
ubuntu@nephio-r1-e2e:~$ kubectl get pods -A --kubeconfig edge01-kubeconfig 
NAMESPACE                      NAME                                                 READY   STATUS     RESTARTS   AGE
config-management-monitoring   otel-collector-6cb84fc5d6-79xzr                      1/1     Running    0          28m
config-management-system       config-management-operator-5c45bf56bb-tc9rl          1/1     Running    0          31m
config-management-system       reconciler-manager-86c5f8cc79-nz88t                  2/2     Running    0          28m
config-management-system       root-reconciler-edge01-bdd54c6f6-kcd7c               4/4     Running    0          28m
free5gc-cp                     free5gc-ausf-7d494d668d-vbhkp                        0/1     Init:0/1   0          17m
free5gc-cp                     free5gc-nrf-66cc98cfc5-g6lnn                         0/1     Init:0/1   0          17m
free5gc-cp                     free5gc-nssf-668db85d54-9x5qz                        0/1     Init:0/1   0          17m
free5gc-cp                     free5gc-pcf-55d4bfd648-5n6hz                         0/1     Init:0/1   0          17m
free5gc-cp                     free5gc-udm-845db6c9c8-t4cmm                         0/1     Init:0/1   0          17m
free5gc-cp                     free5gc-udr-79466f7f86-7bcx8                         0/1     Init:0/1   0          17m
free5gc-cp                     free5gc-webui-84ff8c456c-45hdv                       0/1     Init:0/1   0          17m
free5gc-cp                     mongodb-0                                            0/1     Pending    0          17m
kube-system                    coredns-787d4945fb-x2hjq                             1/1     Running    0          31m
kube-system                    coredns-787d4945fb-xt2jh                             1/1     Running    0          31m
kube-system                    etcd-edge01-5x8xr-sc59z                              1/1     Running    0          31m
kube-system                    kindnet-fd7hg                                        1/1     Running    0          30m
kube-system                    kindnet-kmb2d                                        1/1     Running    0          30m
kube-system                    kindnet-kvv9c                                        1/1     Running    0          29m
kube-system                    kindnet-llk6j                                        1/1     Running    0          29m
kube-system                    kube-apiserver-edge01-5x8xr-sc59z                    1/1     Running    0          31m
kube-system                    kube-controller-manager-edge01-5x8xr-sc59z           1/1     Running    0          31m
kube-system                    kube-proxy-4xm6q                                     1/1     Running    0          31m
kube-system                    kube-proxy-5n4tp                                     1/1     Running    0          29m
kube-system                    kube-proxy-5q8db                                     1/1     Running    0          30m
kube-system                    kube-proxy-nwbvm                                     1/1     Running    0          29m
kube-system                    kube-scheduler-edge01-5x8xr-sc59z                    1/1     Running    0          31m
resource-group-system          resource-group-controller-manager-6cdfc6486d-ldmbd   3/3     Running    0          28m
```

Need a fix for this to continue further testing to close out the issue.
Is there an issue already open for this? If not, I can open one.

@johnbelamaric , Meanwhile, Who can provide the instructions to setup the SMF and UPF so that the ping between them can be tested out. Want to get familar with those instructions until the above pod issues are debugged and resolved?

**Comment by henderiw** [comment]
Yes open PR(s) Are:

#259 -> this is a big one since we moved from clusterCtx to workload cluster. I updated all the test files. So many files, but this is the main change

https://github.com/nephio-project/api/pull/38 -> this allows to validate empty as not ready. Right now I use empty string.

https://github.com/nephio-project/api/pull/39 -> this allows for ipv6 and ipv4. So this allows us to specify what we want rather than hardcoding. It is a small change I want to incorporate after #259 is approved

**Comment by henderiw** [comment]
so I have the specialization running, but to continue the PR chain I need the above 3 approved to proceed.




apiVersion: workload.nephio.org/v1alpha1
--
  | kind: UPFDeployment
  | metadata: # kpt-merge: /upf-
  | name: "upf-cluster03"
  | annotations:
  | internal.kpt.dev/upstream-identifier: 'workload.nephio.org\|UPFDeployment\|default\|upf-'
  | spec:
  | capacity:
  | maxDownlinkThroughput: 10G
  | maxUplinkThroughput: 10G
  | interfaces:
  | - name: n3
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | - name: n4
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | - name: n6
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | networkInstances:
  | - name: vpc-internal
  | interfaces:
  | - n4
  | - name: vpc-internet
  | dataNetworks:
  | - name: vpc-internet
  | pool:
  | - prefix: 172.0.0.0/8
  | interfaces:
  | - n6
  | - name: vpc-ran
  | interfaces:
  | - n3

apiVersion: workload.nephio.org/v1alpha1
--
  | kind: UPFDeployment
  | metadata: # kpt-merge: /upf-
  | name: "upf-cluster03"
  | annotations:
  | internal.kpt.dev/upstream-identifier: 'workload.nephio.org\|UPFDeployment\|default\|upf-'
  | spec:
  | capacity:
  | maxDownlinkThroughput: 10G
  | maxUplinkThroughput: 10G
  | interfaces:
  | - name: n3
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | - name: n4
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | - name: n6
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | networkInstances:
  | - name: vpc-internal
  | interfaces:
  | - n4
  | - name: vpc-internet
  | dataNetworks:
  | - name: vpc-internet
  | pool:
  | - prefix: 172.0.0.0/8
  | interfaces:
  | - n6
  | - name: vpc-ran
  | interfaces:
  | - n3



apiVersion: workload.nephio.org/v1alpha1
--
  | kind: UPFDeployment
  | metadata: # kpt-merge: /upf-
  | name: "upf-cluster03"
  | annotations:
  | internal.kpt.dev/upstream-identifier: 'workload.nephio.org\|UPFDeployment\|default\|upf-'
  | spec:
  | capacity:
  | maxDownlinkThroughput: 10G
  | maxUplinkThroughput: 10G
  | interfaces:
  | - name: n3
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | - name: n4
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | - name: n6
  | ipv4:
  | address: 10.0.0.10/24
  | gateway: 10.0.0.1
  | vlanID: 10
  | networkInstances:
  | - name: vpc-internal
  | interfaces:
  | - n4
  | - name: vpc-internet
  | dataNetworks:
  | - name: vpc-internet
  | pool:
  | - prefix: 172.0.0.0/8
  | interfaces:
  | - n6
  | - name: vpc-ran
  | interfaces:
  | - n3

**Comment by henderiw** [comment]
So the steps for me are:
1. approve the above PR(s)
2. do some further changes in the functions to incorporate the API(s)
3. add the new packages as a consequence of step1/2
4. upload images

**Comment by vjayaramrh** [comment]
I had to do a little hack for now based on https://github.com/nephio-project/nephio-example-packages/blob/main/cluster-capi-kind-docker-templates/docker_machine_template_worker.yaml#L12 that is mountable to make progress.


I had to create a directory /opt/cni/bin/edge01/mongodb and modify the PV yaml file as below to point to the newly created directory and apply the yaml file to create a PV for now
```
ubuntu@nephio-r1-e2e:~$ cat pv-edge01.yaml 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-loc-sc
spec:
  persistentVolumeReclaimPolicy: Delete
    #storageClassName: local-path
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/opt/cni/bin/edge01/mongodb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
```

**Comment by vjayaramrh** [comment]
June 6th Update: 
Followed instructions at https://github.com/nephio-project/test-infra/blob/main/e2e/provision/README.md and was able to execute steps till step 9 with workarounds.
Step 10 that attempts to deploys UPF does not deploy any pods

**Comment by johnbelamaric** [comment]
So, we have free5gc-cp up and running. We have two more PRs to merge to get the operator up and running. And I think Wim nearly has the hydration/specialization work done.

**Comment by gvbalaji** [comment]
Sequence of operations :

- Deploy the clusters
- Set up Networking (Container lab scripts)
- Then deploy NFs (UPF, SMF and AMF)

**Comment by johnbelamaric** [comment]
This is working now. There is still some flakiness, I think due to concurrency issues. But overall it does work.
