### ISSUE TITLE
Templatize UPF IP and DNNs CIDR in SMF configuration

### ISSUE THREAD

**Issue by denysaleksandrov** [nephio-project/nephio#243]
UPF [NodeID](https://github.com/nephio-project/free5gc/blob/main/free5gc-operator/controllers/free5gc_smfcfg.go#L58) and [DNN CIDRs](https://github.com/nephio-project/free5gc/blob/main/free5gc-operator/controllers/free5gc_smfcfg.go#L66) are hardcoded in SMF configuration template. This should be changed to provide UPF IP(s) and DNN(s) via SMFDeployment CR.

**Comment by n2vo** [comment]
https://github.com/nephio-project/free5gc/pull/22
