### ISSUE TITLE
cluster-capi/v3: spec.topology failure

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#245]
I updated the e2e provisioning to use `cluster-capi/v3` (which I tagged after https://github.com/nephio-project/nephio-example-packages/pull/22 merged) and now I get this failure when ConfigSync tries to apply the `cluster-capi-kind` package:

```
          KNV2009: failed to apply Cluster.cluster.x-k8s.io, default/edge1-cluster: admission webhook "validation.cluster.cluster.x-k8s.io" denied the request: Cluster.cluster.x-k8s.io "edge1-cluster" is invalid: spec.topology: Forbidden: can be set only if the ClusterTopology feature flag is enabled

```

I am going to go back to `cluster-capi/v2` for now.

/assign @electrocucaracha @henderiw

**Comment by henderiw** [comment]
ok I already know the root cause here as I changed this by hand in the package. To user our features for kind we need to enable topology=true

which by default is set to false. Example below

- --feature-gates=MachinePool=false,ClusterTopology=true

**Comment by henderiw** [comment]
PR that should fix it
https://github.com/nephio-project/nephio-example-packages/pull/40

**Comment by johnbelamaric** [comment]
Fixed
