### ISSUE TITLE
Add ClusterContext resource in the nephio-workload-cluster  package and align siteCode vs clusterName

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#247]

**Comment by johnbelamaric** [comment]
cc @vjayaramrh

**Comment by henderiw** [comment]
https://github.com/nephio-project/free5gc-packages/pull/17
https://github.com/nephio-project/api/pull/37

**Comment by gvbalaji** [comment]
https://github.com/nephio-project/nephio/pull/269
https://github.com/nephio-project/free5gc-packages/pull/20

**Comment by johnbelamaric** [comment]
this is done
