### ISSUE TITLE
kind workload clusters missing storage class (free5gc mongo db not coming up)

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#256]
Following the steps in https://github.com/nephio-project/test-infra/pull/61 up through step 8, I see the free5gc-cp bring up is stalled.

```
ubuntu@nephio-r1-e2e:~$ kubectl --kubeconfig edge02-kubeconfig -n free5gc-cp describe pvc datadir-mongodb-0
Name:          datadir-mongodb-0
Namespace:     free5gc-cp
StorageClass:  
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/component=mongodb
               app.kubernetes.io/instance=free5gc
               app.kubernetes.io/name=mongodb
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       mongodb-0
Events:
  Type    Reason         Age                     From                         Message
  ----    ------         ----                    ----                         -------
  Normal  FailedBinding  4m59s (x482 over 125m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
ubuntu@nephio-r1-e2e:~$ 
```

**Comment by henderiw** [comment]
can you apple this to see if it works?

kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml

if so we have to build a package with this and add it like the CNI to the mgmt staging repo for the bootstrapped to pick it up and install.

**Comment by denysaleksandrov** [comment]
https://github.com/nephio-project/nephio-example-packages/pull/44

**Comment by johnbelamaric** [comment]
- need to tag package above as 
- need to include in nephio-workload-cluster
- @denysaleksandrov what were the additional steps needed?

**Comment by henderiw** [comment]
this is the package we need to update.

nephio-example-packages % ls nephio-workload-cluster

resource-backend/app/controller/deployment-controller.yaml:        - name: RESOURCE_BACKEND
henderiw@MacBook-Pro nephio-example-packages % ls nephio-workload-cluster 
Kptfile                 apply-replacements.yaml pv-cluster.yaml         pv-kindnet.yaml         pv-rootsync.yaml
README.md               package-context.yaml    pv-configsync.yaml      pv-repo.yaml            workload-cluster.yaml

it is similar to the pv-kindnet.yaml

**Comment by denysaleksandrov** [comment]
https://github.com/nephio-project/nephio-example-packages/pull/45

**Comment by johnbelamaric** [comment]
Done
