### ISSUE TITLE
Sandbox: should we expose Nephio WebUI on a LB IP?

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#258]
Right now, we do not expose the WebUI outside the management cluster. That's partly because we didn't have a way to do it before, but it is also because there is no authentication required for the UI right now. It's possible to configure authentication with an external identify provider, but I don't think we want that in our sandbox environment. We may be able to configure local K8s-based auth, though. So, I wanted to raise the discussion:

1. Should we expose the WebUI on a load balancer port (like we did with Gitea) in the sandbox environment? If we do that, we no longer need to do `kubectl port-forward` to reach the WebUI, though we still need a tunnel to the port, or need to expose the VM port in some other way (see for example: https://github.com/nephio-project/test-infra/pull/60/files#r1215608794).
2. If we do that, should we see if we can enable local k8s-based authentication on the UI? This would mean you have to login, but it would just authenticate with the local K8s cluster, so we can give it a fixed username/password. I think the UI supports that.

**Comment by henderiw** [comment]
I would do this. People should know this is not a production system.

**Comment by johnbelamaric** [comment]
@ChristopherFry currently we just use the service account of the webui to talk to K8s. Is it possible to configure it to authenticate the user against the K8s cluster directly (ie, against a k8s service account), or does it have to use a 3rd part auth provider?

**Comment by gvbalaji** [comment]
Defer after R1.
