### ISSUE TITLE
Add setup inter-cluster networking to demo sandbox

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#270]

**Comment by johnbelamaric** [comment]
- We can take a look at the operator Wim's team developed, time is a concern
- However, as a fallback, we can have a tool that runs after all clusters are created and generates a containerlab topology.

The second option makes horizontal scale out by adding a cluster not really work well.

**Comment by gvbalaji** [comment]
Hold off on  PRs for dynamic inter-cluster networking.

**Comment by gvbalaji** [comment]
For static configuration :
Bring up all clusters
Run container lab 
Wim has scripts for dynamic networking but this can wait post R1.

**Comment by johnbelamaric** [comment]
This is done
