### ISSUE TITLE
Manual test of run of sandbox provisioning in OpenStack

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#272]
Make the changes needed to be able to provision the sandbox and run through the e2e.sh scripts in an Ubuntu VM on OpenStack. This entire flow should be tested:

https://github.com/nephio-project/test-infra/tree/main/e2e/provision

See also https://github.com/nephio-project/nephio/issues/235#issuecomment-1582918293

**Comment by gvbalaji** [comment]
Crashing first time and seems to be working second time.  We may document as a known issue and the workaround in the install guide.

**Comment by johnbelamaric** [comment]
See https://github.com/nephio-project/test-infra/pull/73#issuecomment-1585291441

I think if there are any openstack specifics we want to document, that is the approach I want to take to start. But maybe this will just fall into the "generic ubuntu VM".

**Comment by gvbalaji** [comment]
Liam will write a script for workarounds in this environment.   Hacks directory may be a good choice.

**Comment by johnbelamaric** [comment]
this is done
