### ISSUE TITLE
Manual test of run of sandbox provisioning in vSphere

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#273]
Make the changes needed to be able to provision the sandbox and run through the e2e.sh scripts in an Ubuntu VM on vSphere. This entire flow should be tested:

https://github.com/nephio-project/test-infra/tree/main/e2e/provision

See also https://github.com/nephio-project/nephio/issues/235#issuecomment-1582918293

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/pull/73#issuecomment-1585291441

If there is anything special for vSphere, we should document it as described in that issue.

**Comment by gvbalaji** [comment]
Manual set up of VM on vSphere and then running the provisioning and e2e scripts.

**Comment by denysaleksandrov** [comment]
https://github.com/nephio-project/nephio/issues/317 - blocking issue.

**Comment by denysaleksandrov** [comment]
@johnbelamaric just installed nephio in Ubuntu 20.04 VM running in vSphere. 
Used [this](https://github.com/nephio-project/test-infra/tree/main/e2e/provision#kick-off-installation-on-vm) as an entry point.
Executed all steps, including 007 - xNF Deploy. Everything works fine, except for a minor issue in the latest commit in test-infra, where `$HOME` env variable is mistakingly referenced in init.sh. 

How do we want to document this? Or we can just reflect in this [page](https://github.com/nephio-project/test-infra/tree/main/e2e/provision#kick-off-installation-on-vm) that the procedure is applicable for Ubuntu VM running in vSphere.

**Comment by johnbelamaric** [comment]
Awesome @denysaleksandrov. Yes, I think that page is fine - it will move to the user guide from where it is today.
