### ISSUE TITLE
Add timeout to kpt live apply during sandbox provisioning

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#287]
In a run this morning, I saw `kpt live apply` hang. Everything had been applied to the cluster, but it hung there for a long time. I think by default it waits forever for reconciliation. I think we need to set `--reconcile-timeout` to 10m or something.

I don't know why it didn't think reconciliation was done - I didn't have debug logging on so I couldn't see that detail. So, perhaps something was stalled. But it shouldn't hold up the entire flow if that's the case. As an eventually consistent system, we should be able to handle some timing issues if everything is not all ready at once.

/assign @electrocucaracha

**Comment by gvbalaji** [comment]
@electrocucaracha can you PTAL?

**Comment by electrocucaracha** [comment]
The flag has been [exposed](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/library/kpt.py#L419-L420), it's a matter to consume it. I'm going to create a PR to provide a default value for that. I'll include some additional instructions to provide the Kubernetes resources state after a failure. 

BTW, in case that is needed the Ansible log file is located [here](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/ansible.cfg#L2)

**Comment by gvbalaji** [comment]
PR merged for this.
