### ISSUE TITLE
Missing NAD CRD on workload clusters

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#290]
After specialization finishes, it generates some NADs. When trying to apply those to the cluster, ConfigSync is failing:

```
          KNV1021: No CustomResourceDefinition is defined for the type "NetworkAttachmentDefinition.k8s.cni.cncf.io" in the cluster.
```

I guess we are missing a package that should be installed in all the workload clusters - like we did for kindnet or local-path-provisioner, we need a package with this CRD. Is there a multus package or installation procedure we missed?

@henderiw @denysaleksandrov

**Comment by denysaleksandrov** [comment]
multus is required. that contains NAD CRD.

**Comment by johnbelamaric** [comment]
Yeah, testing the package above

**Comment by johnbelamaric** [comment]
Fixed
