### ISSUE TITLE
Wanna see Nephio in action to understand it's working

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [nephio-project/nephio#294]
how can I download and install nephio and try it out. I didn't find any of the github repo helpful. Can somebody help me with this?

**Comment by johnbelamaric** [comment]
Please wait until after the release and it is documented.

**Comment by johnbelamaric** [comment]
Ok, we have released R1! Please see https://github.com/nephio-project/docs/tree/v1.0.1#nephio-r1
