### ISSUE TITLE
nad-fn prow docker build broken

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#297]
All the others functions are working. I will manually push this one now.

https://prow.nephio.io/view/gs/prow-nephio-sig-release/logs/build-push-image-nad-fn-commit-conf/1668996453583818752

/assign @radoslawc 

cc @kispaljr @henderiw

**Comment by henderiw** [comment]
I have no idea what it is but I have seen issues that the docker file gets corrupted in the and function

**Comment by radoslawc** [comment]
Previous Dockerfile name was 'DockerFile' this was aligned in https://github.com/nephio-project/nephio/pull/293
