### ISSUE TITLE
Rename gce*.sh scripts to more generic names

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#298]
The main install script gce-init.sh is actually applicable for creating sandbox for any environment and not specific to GCE. We are going to document it in the install doc as well. hence we need to rename it to make it more generic. If that causes too much work in terms of changing the dependencies, then writing a generic wrapper around it for official install doc purposes is fine as well. 

Possible new makes discussed are nephio-sandbox.sh, nephio-setup.sh nephio-init.sh .

**Comment by electrocucaracha** [comment]
My proposal is to use `init.sh` or `install_sandbox.sh` given that they are on the Nephio context.
