### ISSUE TITLE
specialization functions prevent saving a package through Porch

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#299]
When editing a *blueprint* - not `--for-deployment` - I want to be able to leave the WorkloadCluster with "example" cluster name. But since Porch runs the function pipeline during a save, I cannot do that (see image below).

The idea would be that we should just do nothing in this case, rather than fail. I think in the workshop we checked the condition to see if the resource had been injected. Or we could check for the annotation that indicates the injected resource name. Or we can come up with some other convention that tells the functions whether or not to act - either an annotation, or an actual sentinel value - ie, treat "example" as not just "it is empty, fail validation" but "it has not been set, so do nothing". I am open to other ideas. But we will need a way to allow users to customize and edit a package *before* specialization.

In this particular case, I wanted to test a fix idea to the package, so I planned to do it by:
1. Clone the example package to a team repo.
2. Make my changes in the team repo.
3. Test the package with a new PVS.
4. If it works, backport those changes to the free5gc-packages repo.

I can still do that, but it will require manual Git operations. I had actually been considering making "create an org version of the example package" in the docs; we would have to fix this first.

![image](https://github.com/nephio-project/nephio/assets/9468083/0ca46a62-ce2d-46a6-b06d-a20bede07275)

/assign @henderiw

**Comment by henderiw** [comment]
https://github.com/nephio-project/nephio/pull/315

**Comment by johnbelamaric** [comment]
fixed
