### ISSUE TITLE
CM don't match in free5gc operator

### ISSUE THREAD

**Issue by henderiw** [nephio-project/nephio#313]
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    101s                default-scheduler  Successfully assigned free5gc-amf/amf-regional-7b56bd6dbb-2fws6 to regional-md-0-jbx5l-6fdf679d86xckjsp-xh7gh
  Warning  FailedMount  37s (x8 over 101s)  kubelet            MountVolume.SetUp failed for volume "amf-volume" : configmap "amf-regional-amf-configmap" not found
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    85s                default-scheduler  Successfully assigned free5gc-smf/smf-regional-654f568756-qn7zf to regional-md-0-jbx5l-6fdf679d86xckjsp-xh7gh
  Warning  FailedMount  21s (x8 over 84s)  kubelet            MountVolume.SetUp failed for volume "smf-volume" : configmap "smf-regional-smf-configmap" not found
ubuntu@nephio-r1-e2e:~$ k --kubeconfig ~/.kube/regional-kubeconfig -n free5gc-amf describe pods
CM>
ubuntu@nephio-r1-e2e:~$ k --kubeconfig ~/.kube/regional-kubeconfig -n free5gc-smf get cm -A
NAMESPACE                      NAME                                 DATA   AGE
config-management-monitoring   kube-root-ca.crt                     1      90m
config-management-monitoring   otel-collector                       1      89m
config-management-monitoring   otel-collector-googlecloud           1      89m
config-management-system       kube-root-ca.crt                     1      90m
config-management-system       otel-agent                           1      89m
config-management-system       reconciler-manager-cm                1      89m
default                        kube-root-ca.crt                     1      90m
free5gc-amf                    amf-regional                         1      19m
free5gc-amf                    kube-root-ca.crt                     1      43m
free5gc-smf                    kube-root-ca.crt                     1      43m
free5gc-smf                    smf-regional                         2      18m
free5gc                        kube-root-ca.crt                     1      56m
kube-node-lease                kube-root-ca.crt                     1      90m
kube-public                    cluster-info                         2      90m
kube-public                    kube-root-ca.crt                     1      90m
kube-system                    coredns                              1      90m
kube-system                    extension-apiserver-authentication   6      91m
kube-system                    kube-proxy                           2      90m
kube-system                    kube-root-ca.crt                     1      90m
kube-system                    kubeadm-config                       1      90m
kube-system                    kubelet-config                       1      90m
kube-system                    multus-daemon-config                 1      90m
local-path-storage             kube-root-ca.crt                     1      90m
local-path-storage             local-path-config                    4      90m
resource-group-system          413d8c8e.gke.io                      0      89m
resource-group-system          kube-root-ca.crt                     1      89m
resource-group-system          resource-group-otel-agent            1      89m

**Comment by denysaleksandrov** [comment]
https://github.com/nephio-project/free5gc/pull/34
