### ISSUE TITLE
Reduce hardcoding of NF parameters

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#340]
For example, the 3GPP parameters should be in a 3GPP resource that can be injected to all packages for a given topology.

/sig automation
/area package-specialization
/area workload-cluster

**Comment by gvbalaji** [comment]
Work with @josephthaliath  and @henderiw  on the design aspects of this.

**Comment by henderiw** [comment]
https://github.com/nephio-project/api/pull/51

**Comment by henderiw** [comment]
https://github.com/nephio-project/nephio/issues/340

**Comment by johnbelamaric** [comment]
Is this fixed with https://github.com/nephio-project/api/pull/51 and https://github.com/nephio-project/api/pull/53 or is there more to do?

**Comment by josephthaliath** [comment]
I was using the latest code, I noticed that "type ObjectReference struct" , the APIVersion , Kind, Name are still optional. @henderiw  somehow the changes Vamshi did not get into the main branch?

**Comment by johnbelamaric** [comment]
To be discussed in tomorrow's meeting

**Comment by henderiw** [comment]
The OAI Core CR:
- the controller code does not use any CRD.

Nothing to is done through CRDs for the core -> OAI controller looks at the structure, package is transparent
