### ISSUE TITLE
OAI RAN KPT packages

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#366]

**Comment by johnbelamaric** [comment]
Packages are done locally

Will make a pull request to the https://github.com/nephio-project/catalog

**Comment by josephthaliath** [comment]
PR raised : https://github.com/nephio-project/catalog/pull/3

**Comment by henderiw** [comment]
updated with latest changes.
https://github.com/nephio-project/catalog/pull/3

**Comment by josephthaliath** [comment]
Initial PR is merged.

**Comment by josephthaliath** [comment]
Readme is updated.
Initial testing completed with R2 infra scripts.
Packages are available here: https://github.com/nephio-project/catalog/tree/main/workloads/oai
