### ISSUE TITLE
OAI core deployment

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#367]
Deploy OAI core services using Nephio principles.

**Comment by arora-sagar** [comment]
Thanks bala. I am doing all the developments here --> https://github.com/OPENAIRINTERFACE/oai-packages/tree/develop. I have created issues for myself.

**Comment by henderiw** [comment]
new NFConfig: done
NF Specializer changes done

Bootstrap controller to be addressed

**Comment by henderiw** [comment]
bootstrap controller PR:
https://github.com/nephio-project/nephio/pull/431

**Comment by arora-sagar** [comment]
It is done here are the packages I haven't create a tag but it is in `r2` branch. https://github.com/OPENAIRINTERFACE/oai-packages/tree/r2
