### ISSUE TITLE
OAI UE simulator KPT package

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#368]

**Comment by johnbelamaric** [comment]
PR will be proposed soon

**Comment by henderiw** [comment]
https://github.com/nephio-project/catalog/pull/3

**Comment by henderiw** [comment]
@josephthaliath  add some documentation on the packages and what they are supposed to do

**Comment by josephthaliath** [comment]
Initial PR is merged. 
https://github.com/nephio-project/catalog/tree/main/workloads/oai

Pending:
1) README update
2) Updates based on R2 infra testing

**Comment by josephthaliath** [comment]
Readme is updated.
Initial testing completed with R2 infra scripts.
Packages are available here: https://github.com/nephio-project/catalog/tree/main/workloads/oai
