### ISSUE TITLE
Initial free5gc UPF package

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#37]
A package using the latest CRD proposal that represents a vendor package for free5gc UPF.

**Comment by henderiw** [comment]
Do we have a repo where we would store these?

**Comment by johnbelamaric** [comment]
Under discussion here: https://github.com/nephio-project/nephio/issues/10

**Comment by johnbelamaric** [comment]
But you can put it in free5gc-packages for now.

**Comment by henderiw** [comment]
created PR.
https://github.com/nephio-project/free5gc-packages/pull/9
