### ISSUE TITLE
Inform PRs if unit test coverage percentage falls below certain percentage

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#374]
Set up the gate to reject the PRs if the unit testing coverage falls below a certain threshold ( 70-80 % may be?)

**Comment by gvbalaji** [comment]
For R2 time frame we will not reject the PR but display informational data.

**Comment by gvbalaji** [comment]
Rado will submit the PR this week .

**Comment by radoslawc** [comment]
https://github.com/nephio-project/test-infra/pull/215
