### ISSUE TITLE
EPIC : Two (or more) NF vendors on the  same infra 

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#380]
This EPIC covers deployment of multi vendor Network functions in the same infrastructure.  This covers

- Common NF Deploy CRs for the 2 NF vendors
- Vendor extensibility for the 2 NF vendors (Free 5GC & OAI)
- Enhance the Infra CRs to meet the needs for NFs-related infra provisioning.

- [x] #391
- [x] #399
- [x] #400
- [x] #401
- [x] #402

**Comment by henderiw** [comment]
wait till R3 to accommodate the generic configuration proposal
