### ISSUE TITLE
Enable Molecule framework integration tests to be invoked automatically

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#381]
For now, we have to run integration tests (thru molecule framework)  manually and locally consuming a lot of time, so should be nice if we can figure out how to include it on the existing prow jobs

Right now Victor has this:
https://github.com/nephio-project/test-infra/pull/86

We need to see how we can do this with Prow.

**Comment by electrocucaracha** [comment]
I have been working on enabling this using the [molecule gce plugin driver](https://github.com/ansible-community/molecule-plugins/blob/main/src/molecule_plugins/gce/driver.py). This approach will require minimum changes and reutilize the existing infrastructure
