### ISSUE TITLE
Completed design proposal for package specialization building blocks

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#39]
Completed design proposal for package specialization building blocks

**Comment by henderiw** [comment]
the skeleton is here. https://docs.google.com/presentation/d/1WUYLZZDzXB5paUBEPc_prEegdn4LFcb7o44itG6XQsM/edit?usp=sharing

The design docs will be added in the respective repo(s)

**Comment by henderiw** [comment]
done
