### ISSUE TITLE
Repos for OAI RAN controllers and packages

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#392]
OAI RAN development will be happening on the Nephio repo unlike the OAI core development which is happening on the OAI repo. All the CRDs will goto the API repo. However under the Nehio github org we need the repos  for
- OAI RAN controllers
- OAI RAN packages.

If we follow the free5gc pattern, then there will be two separate repos for these unless we reorganize the repos for packages to store all the packages in a single repo.

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/oai

**Comment by johnbelamaric** [comment]
RFC: https://github.com/nephio-project/catalog/pull/2/files
