### ISSUE TITLE
Facing issues while deploying free5cg-cp and free5gc-operator 

### ISSUE THREAD

**Issue by sriramgopalvarma** [nephio-project/nephio#403]
Hi @johnbelamaric, I was trying to deploy nephio on a Ubuntu 20.04 vm. I have created it on openstack with given prerequisites. For the first time I have deployed it successfully up to step7 i.e. deploying ams, upf and smf from this url (https://github.com/nephio-project/docs/blob/main/user-guide/exercises.md). I was failed to deploy UERANSIM. So, I thought of redeploying everything. But now I was unable to deploy even free5gc operator and cp i.e. step 5 and 6. "reconciler-manager-86c5f8cc79-h48ms" pod is not coming up so I have deleted the multus pod, so they are up. But rest of free5gc pods are stuck in container creating state. I'm getting the below error.
![24 09 2023_11 07 57_REC](https://github.com/nephio-project/nephio/assets/121871187/98fe80e7-e526-4676-a1fd-64d08a4f16c8)
Can you please help me to fix it.

**Comment by johnbelamaric** [comment]
Looks like a missing CNI plugin - @s3wong any ideas?

**Comment by efiacor** [comment]
Could be related to this issue
https://nephio.slack.com/archives/C03L6Q8LFHD/p1695770414222929?thread_ts=1694584389.781269&cid=C03L6Q8LFHD

**Comment by johnbelamaric** [comment]
@sriramgopalvarma thanks for the issue, this should be fixed now, it was because we didn't pin one of our packages to a particular released image, so when the image changed in the upstream project, it broke our release. This has been fixed.

Please open an new issue if you see something like this again.
