### ISSUE TITLE
Create Example package representing a topology of three Network Functions

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#42]
Example package representing a topology of those NFs (ala [this one](https://github.com/johnbelamaric/nephio-testorg-packages/tree/main/cachingdns-topology))

**Comment by johnbelamaric** [comment]
@johnbelamaric: create a nephio-example-packages repo for a "playground"

**Comment by johnbelamaric** [comment]
Ok, added this repo: https://github.com/nephio-project/nephio-example-packages

@liamfallon you should fork that and build out your package in the fork and we will merge it like other PRs

**Comment by liamfallon** [comment]
@johnbelamaric Thanks John, will do.

**Comment by liamfallon** [comment]
[https://github.com/nephio-project/nephio-example-packages/pull/4](url)

**Comment by johnbelamaric** [comment]
Merged!

**Comment by liamfallon** [comment]
:smiley:
