### ISSUE TITLE
Porch PackageVariant configuration injection feature

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#43]
Implement config injection feature either in Porch or locally (then upstream in Porch)

**Comment by gvbalaji** [comment]
If this is done in Porch there may be a need to sign Google CLA

**Comment by johnbelamaric** [comment]
Did you get a chance to take a look, @SimonTheLeg ?

**Comment by SimonTheLeg** [comment]
Not yet, I am stuck with this one https://github.com/nephio-project/nephio/issues/117#issuecomment-1532620295
