### ISSUE TITLE
Test infra set up for OAI RAN and core testing

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#439]
We need a set up  to test OAI RAN and core as described in the deployment architecture. For this we need to set up clustes in test  infra. At this time we can test free5gc and OAI separately.

**Comment by gvbalaji** [comment]
https://drive.google.com/file/d/1KVgc4ohmdocfExMG0F_9N_iBCgu9Pcep/view
@arora-sagar @josephthaliath please see if this deployment is still accurate.

**Comment by electrocucaracha** [comment]
I've been thinking about this enablement, and I've concluded that the following tasks are required:

1. Create an environment variable to specify the End-to-End scenario to execute, e.g `${NEPHIO_E2E_TYPE:-free5gc}` and move the existing testing scripts from `e2e/tests/` to `e2e/tests/free5gc` and update their references. [medium]
2. Create new sequential bash scripts in `e2e/tests/oai` for End-to-End scenario. These scripts can reuse the assertion and waiting functions previously defined for `free5gc`. [large]
3. Define new Terraform variables to control and pass the End-to-End scenario to execute. [small]
4. Create new on-demand and periodic prow jobs that cover the new `${NEPHIO_E2E_TYPE:-oai}` e2e scenario. [small]

If you don't mind, I'll start with the first task.

**Comment by arora-sagar** [comment]
@electrocucaracha sure you can start. I just recommend using some generic names or just using `r2` nothing specific to `oai` later if we adapt free5GC a bit we can use the same infra for free5GC. 

I have made slight changes in the diagram to add new VLAN IDs and VPC. Also, the naming of the clusters is different than R1. It is done to accommodate naming from O-RAN (Core, Regional, and Edge Cluster). For cluster naming, we need to make changes in the packages and their labels. 

For networking, we need to make changes in 

1. `test-infra/e2e/tests/002-topo.gotmpl` change the name from free5gc to something generic (I don't recommend using oai either just something generic or `r2-network`)
2. `test-infra/e2e/provision/hacks/vlan-interfaces.sh` add new vlan ids in `for i in {2..4}` change it to `for i in {2..6}`
3. Update the `nephio-example-packages/network` with new vpcs 
4. Update `test-infra/e2e/provision/hacks/network-topo.sh` with new cluster labels and network name

**Comment by electrocucaracha** [comment]
Initial tasks detected for this implementation:

- [x] Create an environment variable to specify the End-to-End scenario to execute, e.g ${NEPHIO_E2E_TYPE:-free5gc} and move the existing testing scripts from e2e/tests/ to e2e/tests/free5gc and update their references. [Completed](https://github.com/nephio-project/test-infra/pull/218)
- [ ] Create new sequential bash scripts in e2e/tests/oai for End-to-End scenario. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/ba4388533a71c9c9827c00cf7cc7665700e0ad50)
- [ ] Define new Terraform variables to control and pass the End-to-End scenario to execute. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/3fb5c9ff16fffd9cf7f4cb2ef2111298ed83438e)
- [ ] Create new on-demand and periodic prow jobs that cover the new ${NEPHIO_E2E_TYPE:-oai} e2e scenario. [Backlog]
- [ ] Rename topology from `free5gc` to something generic. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/0ec2f0e8c168e5f7f57774aa6a5bb57d390ca648)
- [ ] Add new VLAN IDs in for i in {2..4} change it to for i in {2..6}. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/ad1e6d8bc828efbfbfff7b9c2f04ee627efcca66)
- [ ] Update the nephio-example-packages/network with new vpcs. [In Progress](https://github.com/nephio-project/catalog/pull/7)
- [ ] Update `test-infra/e2e/provision/hacks/network-topo.sh` with new cluster labels and network name. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/ba4388533a71c9c9827c00cf7cc7665700e0ad50)

**Comment by henderiw** [comment]
script updates to be tested

**Comment by josephthaliath** [comment]
PR: https://github.com/nephio-project/test-infra/pull/227
