### ISSUE TITLE
Investigate the  UI changes needed  for the workshop UI,  and make changes 

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#44]
This issue is about cleaning up the existing UI code used in the workshop and make it relevant to R1 release  
This includes:
1. Figure out the gaps with the existing UI 
2. Figure out the work elements
3. Execute on work elements where possible

**Comment by henderiw** [comment]
We need to evaluate the scope here. A session with Chris and John would be required,

**Comment by ganchandrasekaran** [comment]
I myself not a GUI expert, I will coordinate with @Saheer (saheer.m@samsung) who has hands-on with react-framework for this task.

**Comment by gvbalaji** [comment]
thanks . We need to add Saheer to github team.

**Comment by johnbelamaric** [comment]
Ad Hoc zoom meeting 3/31 at 8am: https://zoom.us/j/91557349874

**Comment by gvbalaji** [comment]
Adding the UI planning doc by John here for details.
https://docs.google.com/document/d/1qb-m-p-Fsp8rrjdAygm5VQLwZwcN4A2SlXHkyy8WQaY/edit#heading=h.pwhus9slex2g

**Comment by johnbelamaric** [comment]
Thanks Bala

**Comment by johnbelamaric** [comment]
I don't think any changes are needed, instead we can just use the main branch of the Porch UI repo. All changes we need in R1 that were done for the workshop-specific Nephio UI have been ported back to that main branch.
