### ISSUE TITLE
Porch migration to Nephio

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#465]
Tracking issue for the migration discussed here: https://github.com/nephio-project/nephio/discussions/450

*Migration*
- [x] Create new repository
- [x] Migrate v0.0.35 server code to new repository
- [x] Get builds working in new repository
- [x] Get base CI working in new repository
- [x] Get Porch e2e tests working new repository
- [x] Migrate v0.0.35 CLI code to a new `porchctl` CLI tool (instead of `kpt alpha`)
- [x] Get the e2e for the CLI working (https://github.com/nephio-project/porch/pull/10)
- [ ] Get the CI working for the e2e tests (server and CLI, see https://github.com/nephio-project/porch/pull/4#issuecomment-1861976730 and https://github.com/nephio-project/porch/pull/10#issue-2049702913 for relevant notes)
- [x] https://github.com/nephio-project/nephio/issues/481
- [ ] Consider re-introducing the changes in https://github.com/kptdev/kpt/pull/4094, but with additional E2E tests and related fixes (it seems to have some concurrency problems). This is in https://github.com/nephio-project/porch/pull/8
- [ ] Migrate the Porch documentation to Nephio docs

*Clean Up*
- [x] Remove unused controllers
- [ ] Move fleet-sync GCP-specific controller to a separate repo, and consider re-instating other GCP-specific controllers if desired
- [ ] Remove the "Task List" concept from PackageRevision
- [ ] Remove the Function CRD, as we are not using it
- [ ] Remove the "Package" CRD, as it is not fully implemented
- [ ] Consider removing OCI support. We don't use it today, and it is not as well exercised as the Git support

**Comment by johnbelamaric** [comment]
For the Porch e2e tests, it does some of them now but not the ones that require a cluster. We need:

- Image build and push working for PRs for the nephio-project/porch repo
- The `make ci-test-porch` needs to create a Kind cluster, deploy the code (`make deploy`), then set `E2E=1` and do the `make test`. Right now, it doesn't set `E2E` so those tests are skipped.

See also
https://github.com/nephio-project/porch/pull/4#issuecomment-1861976730 and the subsequent comments.

**Comment by johnbelamaric** [comment]
@electrocucaracha can you help with the above?

**Comment by johnbelamaric** [comment]
Once this is done, we will want to update the docs to all use `porchctl` instead of `kpt alpha`. We will still use `kpt` for some things (like function execution, etc.).

**Comment by efiacor** [comment]
> Once this is done, we will want to update the docs to all use `porchctl` instead of `kpt alpha`. We will still use `kpt` for some things (like function execution, etc.).

Done

**Comment by efiacor** [comment]
> For the Porch e2e tests, it does some of them now but not the ones that require a cluster. We need:
> 
>     * Image build and push working for PRs for the nephio-project/porch repo
> 
>     * The `make ci-test-porch` needs to create a Kind cluster, deploy the code (`make deploy`), then set `E2E=1` and do the `make test`. Right now, it doesn't set `E2E` so those tests are skipped.
> 
> 
> See also [nephio-project/porch#4 (comment)](https://github.com/nephio-project/porch/pull/4#issuecomment-1861976730) and the subsequent comments.

PR raised here - https://github.com/nephio-project/porch/pull/21

**Comment by liamfallon** [comment]
Triaged
Triage Comment: Complete in R3

**Comment by efiacor** [comment]
Closing with the following exceptions.

Outstanding items:

- Task List removal/reimplementation. Issue created here - https://github.com/nephio-project/nephio/issues/822
- OCI support will be retained for now
- Package (PorchPackage) CR will be retained for now.
