### ISSUE TITLE
porchctl rpkg push fails because .KptRevisionMetadata file is not created

### ISSUE THREAD

**Issue by liamfallon** [nephio-project/nephio#471]
In Porch in Nephio I created a new pacakage and then tried to push the content to it. The push fails due to the hidden .KptRevisionMetadata file being missing.

```
porchctl -n porch-demo rpkg init zooby --repository=management --workspace=v1                                   
management-662178419b988802fffab21e30ddf449ed6f4e7d created
porchctl -n porch-demo rpkg push management-662178419b988802fffab21e30ddf449ed6f4e7d blueprints/network-function
Error: failed to parse ".KptRevisionMetadata" of PackageRevisionResources porch-demo/management-662178419b988802fffab21e30ddf449ed6f4e7d: failed to extract objects: unhandled node kind 8 
```

When I do the following, I can work around the bug:
```
porchctl -n porch-demo rpkg pull management-662178419b988802fffab21e30ddf449ed6f4e7d
....

items:
- apiVersion: ""
  kind: KptRevisionMetadata
  metadata:
    name: management-662178419b988802fffab21e30ddf449ed6f4e7d
    namespace: porch-demo
    creationTimestamp: "2024-01-08T16:37:45Z"
    resourceVersion: 4029b60df8f22a0fe86340e7c9cc603cdaa740fb
    uid: uid:zooby:v1
    annotations:
      config.kubernetes.io/index: '0'
      internal.config.kubernetes.io/index: '0'
      internal.config.kubernetes.io/path: '.KptRevisionMetadata'
      config.kubernetes.io/path: '.KptRevisionMetadata'
......
```
I added that content to a .KptRevisionMetadata file in the directory where the KPT package is and the subsequent porchctl rpkg push worked

The following command is a one-liner for this:
```
porchctl -n porch-demo rpkg pull management-662178419b988802fffab21e30ddf449ed6f4e7d | yq '.items[0]' > blueprints/network-function/.KptRevisionMetadata

```

**Comment by johnbelamaric** [comment]
Thanks Liam. I suspect this also exists in `kpt alpha rpkg init`. We should update `porchctl rpkg init` to create this file after the init is done. The file basically contains the git hash for the commit that the files represent.

**Comment by liamfallon** [comment]
Thinking about this one, this happens because the user has not done a porchctl rpkg pull before the porchctl rpkg push so the current behaviour is OK, the user should always do a porchctl rpkg pull after a porchctl rpkg init to initialize the package ont heir local directory. However, the current error message is cryptic in the extreme so I propose to raise a PR to improve the error message.
