### ISSUE TITLE
Updating free5gc packages + move to catalog repo

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#472]
Updating free5gc packages + move to catalog repo

For details :
https://nephio.slack.com/archives/C03MB5GRATS/p1702481453779489

**Comment by liamfallon** [comment]
@arora-sagar will submit the last package.

**Comment by gvbalaji** [comment]
Sagar will push the PR for @henderiw .

**Comment by arora-sagar** [comment]
All packages are now in the catalog repository.
