### ISSUE TITLE
Check OAI using all the latest code

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#475]
Check OAI using all the latest code 
Use main for package reference + latest for images for now

**Comment by electrocucaracha** [comment]
These are the Nephio components detected:
* ConfigSync:
 - [Catalog PR](https://github.com/nephio-project/catalog/pull/15)
 - Test infra PR - TBD
* Nephio Controller/Operator:
 - [Catalog PR](https://github.com/nephio-project/catalog/pull/14)
 - Test infra PR - TBD
* Porch: 
 - [Catalog PR](https://github.com/nephio-project/catalog/pull/13)
 - [Test infra PR](https://github.com/nephio-project/test-infra/pull/229)

**Comment by electrocucaracha** [comment]
The latest [PR change](https://github.com/nephio-project/test-infra/pull/229) uses the latest Nephio Code
