### ISSUE TITLE
[docs]: Important details are hidden in the documentation

### ISSUE THREAD

**Issue by CsatariGergely** [nephio-project/nephio#495]
The documentation uses the `<details>` and `<summary>` raw html tags a lot to hide console outputs in the rendered documentation. This approach decreases the readability of the documentation as the output of the commands is always relevant. 
I would propose to remove the drop downs and just simply render all the outputs to the documentation.

**Comment by CsatariGergely** [comment]
@liamfallon, @efiacor, @lovesprung, @spaitsbence

**Comment by efiacor** [comment]
Hi @CsatariGergely 
I would somewhat agree. Maybe for small sections of sample output we can remove the drop downs. But for anything larger (not sure what metric to use here?) we should keep the drop downs to avoid excessive scrolling for the reader.

**Comment by CsatariGergely** [comment]
Sure, I think It is okay do define a limit or something, I would even set this limit to quite high, like 50 lines....
