### ISSUE TITLE
Documentation site colors

### ISSUE THREAD

**Issue by CsatariGergely** [nephio-project/nephio#509]
The current docs page uses the Docsy default colors. I think we should change them to more follow the color scheme of Nephio. 

The Docsy theme allows to set a primary and a secondary color, setting the colors form the Nephio logo did not bring the best results: 
![image](https://github.com/nephio-project/nephio/assets/11458775/138aa3fa-e950-4627-943b-a50cfbb51b08)
![image](https://github.com/nephio-project/nephio/assets/11458775/e15eb764-c191-4c38-8dd1-396af8dee1f7)

So the big question is what colors to use. 
* I can set the header to use a different color, so the Nephio logo would be visible
* Or I can set different primary and secondary colors. 
Any opinions?

**Comment by liamfallon** [comment]
I agree, the colour scheme above does not look very well.
