### ISSUE TITLE
Upgrade to Go 1.22

### ISSUE THREAD

**Issue by tliron** [nephio-project/nephio#510]
Things to do (please add more!):

* Update Makef and Docker files to use/require go 1.22.0 for builds.
* Change all `go.mod` files with the `go 1.22` directive.
* We often use `reflect.TypeOf()`, but in most cases we should change to the new `reflect.TypeFor[]` generic function.

**Comment by liamfallon** [comment]
There are a few PRs to go through before this issue can be closed.

**Comment by liamfallon** [comment]
The PR for the Nephio repo is not merged yet.
