### ISSUE TITLE
Include License Scanning 

### ISSUE THREAD

**Issue by VedRatan** [nephio-project/nephio#546]
https://clomonitor.io/docs/topics/checks/#license-scanning

See: #536

**Comment by gvbalaji** [comment]
This may have been already done.

**Comment by radoslawc** [comment]
We already run licensing compliance scanners on every PR as well on whole codebase using Fossology, Scancode-toolkit and Lichen. There is also standalone Fossology instance that scans whole codebase: https://fossology.nephio.io/repo/
Example results: 
https://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_nephio/483/presubmit-nephio-fossology/1785665326231326720
https://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_nephio/483/presubmit-nephio-scancode-toolkit/1785665326172606464
I'll add that information to .clomonitor.yml files
