### ISSUE TITLE
Some porchctl rpkg subcommands respond on standard error on successful executions

### ISSUE THREAD

**Issue by liamfallon** [nephio-project/nephio#562]
Some `porchctl rpkg` commands respond on stderr when the command completes successfully.

The `init` and `copy` commands respond on stdout.

The `pull` and `push` commands have no response.

The `propose`, `approve`, `propose-delete` and `delete` subcommands exhibit this behaviour, see below:
```
porchctl rpkg propose -n porch-demo management-8b80738a6e0707e3718ae1db3668d0b8ca3f1c82 > /tmp/aaa.txt
management-8b80738a6e0707e3718ae1db3668d0b8ca3f1c82 proposed

porchctl rpkg approve -n porch-demo management-8b80738a6e0707e3718ae1db3668d0b8ca3f1c82 > /tmp/aaa.txt
management-8b80738a6e0707e3718ae1db3668d0b8ca3f1c82 approved

porchctl rpkg propose-delete -n porch-demo management-49580fc22bcf3bf51d334a00b6baa41df597219e
management-49580fc22bcf3bf51d334a00b6baa41df597219e proposed for deletion

porchctl rpkg delete -n porch-demo management-2eeaaf7c1c41c8202687da7420d2a6a1cdaba051 > /dev/null
management-2eeaaf7c1c41c8202687da7420d2a6a1cdaba051 deleted
```

All the subcommands of `porchctl rpkg` should be checked to ensure they respond on stdout in successful executions and stderr on failed executions.

**Comment by kushnaidu** [comment]
Hello @liamfallon, 
the code is merged. 
Can we close this ticket?

**Comment by liamfallon** [comment]
I saw that you will riase a PR to do unit tests for the changed commands. Let's wait for that before closing the issue.

**Comment by kushnaidu** [comment]
@liamfallon, perfect. Will do that.

**Comment by liamfallon** [comment]
Fixed in:
https://github.com/nephio-project/porch/pull/30
https://github.com/nephio-project/porch/pull/33

**Comment by liamfallon** [comment]
Fixed in:
https://github.com/nephio-project/porch/pull/30
https://github.com/nephio-project/porch/pull/33
