### ISSUE TITLE
Porch function runner pod evaluator should allow for pod templating

### ISSUE THREAD

**Issue by nagygergo** [nephio-project/nephio#571]
Pods that are generated by the pod runtime for porch kpt functions are quite barebones descriptions of pods, lacking security configurations, resource requests and limits, node labels and tolerations, affinity, anti-affinity rules. https://github.com/nephio-project/porch/blob/main/func/internal/podevaluator.go#L522

These might be specific to the implementing project, so porch should offer a mechanism to consume pod templates that the podevaluator would fill for kpt function wrapping.

**Comment by liamfallon** [comment]
Triaged
