### ISSUE TITLE
Deploy Nephio management cluster components on real k8s

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#577]

**Comment by vjayaramrh** [comment]
The PR for deploying management components is at https://github.com/nephio-project/test-infra/pull/269

**Comment by dkosteck** [comment]
This has now been validated on an Ubuntu 20.04 VM using https://github.com/nephio-project/test-infra/pull/269. 

Deployment of the K8s cluster was done using https://github.com/nephio-project/test-infra/pull/46.

After the cluster was installed and verified, the context was pulled with `kubectl config get-contexts` and passed to the init script located on the non_kind_k8s branch of the same fork: https://github.com/nephio-project/test-infra/pull/269. 
 
This was then verified by forwarding the ports for the webui and gitea on the jump host, as documented here: https://docs.nephio.org/docs/guides/install-guides/
