### ISSUE TITLE
Porch-controllers is not defining any rights for porch repositories and does not defined watch rights

### ISSUE THREAD

**Issue by nagygergo** [nephio-project/nephio#588]
The controller-runtime's caching client is setting up watches by default for repositories and for the wildcard resources used by packagevariantSet controller. The defined rbac configuration is requesting rights to watch resources.

[//+kubebuilder:rbac:groups=*,resources=*,verbs=list](https://github.com/nephio-project/porch/blob/8a84339f9ee64a44b9d1225d604c2527b217d0a7/controllers/packagevariantsets/pkg/controllers/packagevariantset/packagevariantset_controller.go#L76)

Also, as a side improvement, it would be good to call out that the packageVariantSet controller requires get/list/watch rights for repository resources in the rbac configurations

**Comment by kushnaidu** [comment]
PR created - https://github.com/nephio-project/porch/pull/56

**Comment by kushnaidu** [comment]
Code is merged, Issue is not seen after the merge. closing the ticket.
