### ISSUE TITLE
Docs breadcrumb links are wrong

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#591]
Hi team,

The breadcrumb links in the docs:

![image](https://github.com/nephio-project/nephio/assets/9468083/26605978-77a4-4242-83fc-3b0c6b4351eb)

link to https://nephio.org/docs instead of https://docs.nephio.org, which results in a 404.

**Comment by efiacor** [comment]
Can be closed.
Fixed with docs#125

**Comment by johnbelamaric** [comment]
Awesome, thanks!

/close
