### ISSUE TITLE
Docs for installation guides need a little re-org

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#592]
The "Guides" section in the docs includes "installation guides". But that links directly to the "demo environment" installation, rather than allowing the user to pick between a "demo" and "bring your own cluster", which is really the first decision they need to make. The left hand menu lists all the different environments without this categorization, so it's sort of confusing. I think we need two sections in the "install guides", one for the demo environment, and one for BYOC.

![image](https://github.com/nephio-project/nephio/assets/9468083/f05965c2-4342-4d35-85ed-deaa2352fc6c)

**Comment by CsatariGergely** [comment]
Fixed by https://github.com/nephio-project/docs/pull/148
