### ISSUE TITLE
Remove our local fork of go-git

### ISSUE THREAD

**Issue by liamfallon** [nephio-project/nephio#651]
Original issue URL: https://github.com/kptdev/kpt/issues/3268
Original issue user: https://github.com/mortent
Original issue created at: 2022-05-27T20:13:21Z
Original issue last updated at: 2022-05-27T20:13:21Z
Original issue body: After https://github.com/go-git/go-git/pull/514 is merged we can go back to [go-git](https://github.com/go-git/go-git) module rather than using [our fork](https://github.com/platkrm/go-git)

Context: https://github.com/GoogleContainerTools/kpt/pull/2990

Original issue comments:

**Comment by efiacor** [comment]
Change merged in https://github.com/nephio-project/porch/pull/46
