### ISSUE TITLE
Blueprint isn't immediately available after creation

### ISSUE THREAD

**Issue by liamfallon** [nephio-project/nephio#678]
Original issue URL: https://github.com/kptdev/kpt/issues/3270
Original issue user: https://github.com/mortent
Original issue created at: 2022-05-27T22:03:06Z
Original issue last updated at: 2023-01-26T04:23:43Z
Original issue body: Sometimes the blueprint doesn't seem to exist immediately after creation. 

It might be related to refreshing the cache, but that usually just means that the `main` twin of a package shows up a bit late.

Original issue comments:

**Comment by kushnaidu** [comment]
PR merged, closing the ticket.
