### ISSUE TITLE
Implement code and unit tests for AMF NF controller  in free5GC operator

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#76]
Implement code and unit tests for AMF NF controller in free5gc operator 
Readme with functional specs.

[Parent](https://github.com/nephio-project/nephio/issues/23) issue.

**Comment by gvbalaji** [comment]
Refer to the existing implementation here for reference for UPF.

https://github.com/nephio-project/nephio-pocs/tree/main/free5gc-operator
https://github.com/nephio-project/nephio-pocs/blob/main/free5gc-operator/controllers/upfdeploy_controller.go

**Comment by NMSVishal** [comment]
Hi Team, 
The above task has been assigned to myself and @Ronak joshi.

**Comment by gvbalaji** [comment]
Vishal Varvate and Ronak Joshi are working on this item

**Comment by NMSVishal** [comment]
Working along side with @Ronak Joshi for nephio #89.

It seems nephio#76 is depends on the nephio#89 ,so we (myself and Ronak )are trying to finish the nephio#89 first.
