### ISSUE TITLE
Add R3 Release Note

### ISSUE THREAD

**Issue by CsatariGergely** [nephio-project/nephio#769]

**Comment by adetalhouet** [comment]
FYI - I'm trying to have all SIGs contribute their release notes in the following document: https://docs.google.com/document/d/1Ce42YycAhTtb30BxMsdwmBYGTtCoIeBTrFBs5nvX7gA/edit#heading=h.g5jlhcnz1bpj

Ultimately, SIG3 owns the final version. But for tracking purposes, you can relate to the above doc.
