### ISSUE TITLE
The bootstrap-integration test fails despite an ansible variable defined in molecule.yml file

### ISSUE THREAD

**Issue by vjayaramrh** [nephio-project/nephio#773]
The test complains of undefined variable file despite it being defined in the molecule.yml file, this needs to be investigated further and root caused. Refer http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/269/bootstrap-integration/1805388473121640448#1:build-log.txt%3A545 (cc: @electrocucaracha @radoslawc @liamfallon )

```
 TASK [Include bootstrap] *******************************************************
ERROR! 'tag_nonkind_k8s' is undefined
fatal: [int-focal-vm-bootstrap-289968054]: FAILED! => {"changed": false, "reason": "'tag_nonkind_k8s' is undefined"} 
```

**Comment by electrocucaracha** [comment]
@vjayaramrh this issue is only happening with the changes that you are introducing in your PR, and it's not reproducible in main branch. So, I suggest closing this issue and fix it on your change.

**Comment by vjayaramrh** [comment]
@electrocucaracha What is the fix?

**Comment by vjayaramrh** [comment]
Closing issue as no longer defining a variable
