### ISSUE TITLE
Implement code and unit tests for UPF NF controller in free5gc operator

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#78]
Implement code and unit tests for UPF NF controller in free5gc operator
Refer to the existing implementation here for reference for UPF.

https://github.com/nephio-project/nephio-pocs/tree/main/free5gc-operator
https://github.com/nephio-project/nephio-pocs/blob/main/free5gc-operator/controllers/upfdeploy_controller.go

**Comment by tliron** [comment]
See also Orange's [fork](https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator)

**Comment by denysaleksandrov** [comment]
https://github.com/nephio-project/free5gc/pull/4

**Comment by denysaleksandrov** [comment]
@s3wong is it ok to close this one?

**Comment by s3wong** [comment]
@denysaleksandrov Yes, please go ahead. Good progress and making it on time for end of sprint 1
