### ISSUE TITLE
Design and document the high-level design for Nephio R1

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#8]
We need to come up with the design document that describes the components, flows and interactions. The design document should also explain how the use cases are met by the proposed design. 

This story comprises of following sub tasks. These may be part of same document but could be worked in parallel. 
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33

See also:

- [About – Nephio](https://nephio.org/about/)
  - [Functional Blocks Diagram](https://nephio.org/wp-content/uploads/sites/6/2022/04/Nephio-About-Figure-2-Final.png)
  - [Reference architecture component diagram](https://nephio.org/wp-content/uploads/sites/6/2022/04/Nephio-About-Figure-3-Final-1.png)
- [GitHub - nephio-project/one-summit-22-workshop](https://github.com/nephio-project/one-summit-22-workshop#summary-of-component-code) 
- [[Public] Nephio Components](https://docs.google.com/document/d/1wd-ht4i9YbScVicgUKcZ9_18Xysg2_3N3IuaCper14Q/edit?usp=share_link&resourcekey=0-YsVEzeyveG-otxcV0YpU5w)
- [Nephio-component-discussion (Nokia).pdf](https://drive.google.com/file/d/1j-1sNMyenoSoxwPK1e70d8dyy5XiwaOA/view?usp=share_link)
- [R1 uses cases and gaps](https://docs.google.com/presentation/d/1Fdi-7QQEFxtI7kDyuWoXQIKDumo_maFZGpGADgsdjSE/edit?usp=share_link)
- [Component Landscape #1](https://docs.google.com/drawings/d/1eqxa-9rRNskg9JOY35iCnxBJwg2cIAdz_PE80HaKwlw/edit?usp=sharing)
- [Nephio Release 1: CRDs proposal ](https://docs.google.com/document/d/1cD-Lo-isvi1vN-G_TimPqIEU_eXp2H3a9vUIaAyH6Ug/edit?usp=sharing)
- [Google Seed Code to Nephio R1](https://docs.google.com/document/d/17mbU4F1vsRidgvBabwSO9K-_dHZvEaMWSnA65s5CDGs/edit?usp=sharing&resourcekey=0-H4y3XUVAebBHPXk8WC4RdA) 
- [Nephio End-to-End User Journey.png](https://drive.google.com/file/d/1G9NuPqcmLin5Ot4NrePMJvWJkfHpG0Mt/view?usp=share_link)
- [NF Interface/IP Usage](https://docs.google.com/presentation/d/1K5Fl7UfmuNpRuXDzu1x7YNvK7DsHeuGmxg3D_PHX1bI/edit?usp=sharing)

**Comment by johnbelamaric** [comment]
Should we revisit this issue in light of the latest plans?

**Comment by johnbelamaric** [comment]
@gvbalaji should we close this and the sub-issues in favor of the docs we have so far? Or should we plan to deliver this as part of the future docs? We probably need a comprehensive documentation plan for R2 and beyond.

**Comment by johnbelamaric** [comment]
I am going to close these out as covered by the current docs - we can revisit docs in R2.
