### ISSUE TITLE
Porch approval takes more time with each package in the repository

### ISSUE THREAD

**Issue by nagygergo** [nephio-project/nephio#812]
As part of https://github.com/nephio-project/porch/pull/99 a refresh of the cache after approval was introduced. This can cause porch to time out when approving the package. 

![image](https://github.com/user-attachments/assets/2230026a-c34c-4691-86b0-b98fafbd0a1a)

The timeout seems to happen between 50 and 100 packages, and it takes about 40 seconds before it times out.

**Comment by efiacor** [comment]
Is this one also related?
https://github.com/nephio-project/porch/pull/87

**Comment by kushnaidu** [comment]
PR created - https://github.com/nephio-project/porch/pull/129
