### ISSUE TITLE
Inconsistent behavior between approval of faulty blueprints and allowing them to be cloned.

### ISSUE THREAD

**Issue by nagygergo** [nephio-project/nephio#818]
There is an inconsistency between being able to push propose and approve faulty packageRevisions and being able to clone them.
Either faulty packageRevisions should not be approvable, or it should be possible to clone faulty packagerevisions.

Steps to reproduce:
1. Init porch package
2. pull porch package
3. modify a pulled package: add a kpt function with configuration that will fail
4. push the modified porch package. You will face a function execution error.
5. despite the faced issue the modified porch package was pushed to 'blueprints' repo; do its propose and approve 
6. check the modified porch package is in 'Published' state and its 'main' revision appeared 
7. clone 'Published' in 'blueprints' repo package to 'deployments' repo

Expected result: a cloned package appeared in 'deployments' repo, its status is 'Draft'
Actual result: a schema validation issue was faced again; any package was cloned to 'deployments' repo

**Comment by nagygergo** [comment]
This should only be applicable in case the kpt function was executed, and it returned an error, but in case the kpt functions were not able to execute, porch should not allow the next action (reject the change on the packageRevision with 500)?

**Comment by Catalin-Stratulat-Ericsson** [comment]
I believe this has been solved with the merging of https://github.com/nephio-project/porch/pull/145.
This will be marked as done for now.
