### ISSUE TITLE
UPFDeployment definition check-in to nephio-project/api

### ISSUE THREAD

**Issue by s3wong** [nephio-project/nephio#85]
Utilize the defined Nephio CRD structs including capacity, datanetworks/names, interfaces to build UPFDeployment, which the free5gc operator will be watching / reconciling

Also, preserve the free5gc extension CRD used during ONE Summit (image path for UPF) as separate from the main UPFDeployment, check that one into nephio-project/free5gc-packages

Also define the statuses according to this [doc](https://docs.google.com/document/d/1cD-Lo-isvi1vN-G_TimPqIEU_eXp2H3a9vUIaAyH6Ug/edit#heading=h.e3i35mj5jyac) for now. Keep in mind that any evolution of the UPFDeployment status definition will affect EdgeWatcher

**Comment by denysaleksandrov** [comment]
Do we need to create a separate folder in nephio-project/free5gc-packages project? like api/?
Or extension "imageconfig" CRD should be checked-in the free5gc-operator folder?

**Comment by s3wong** [comment]
> Do we need to create a separate folder in nephio-project/free5gc-packages project? like api/? Or extension "imageconfig" CRD should be checked-in the free5gc-operator folder?

In general, CRDs (the actual "definitions") should either be checked into api repo or for specialized ones (like those only for free5gc) we should just have them in free5gc repo.

free5gc-packages are for the actual yaml with dummy values such that the mutators or injectors can customize those cloned packages with per instance values. That repo isn't meant for actual CRDs

**Comment by denysaleksandrov** [comment]
https://github.com/nephio-project/api/pull/8
